apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-api
  namespace: rag-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query-api
  template:
    metadata:
      labels:
        app: query-api
    spec:
      containers:
        - name: query-api
          image: k8s-rag/query-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: CHROMA_HOST
              value: "chroma-service"
            - name: CHROMA_PORT
              value: "8002"
            - name: CHROMA_COLLECTION
              value: "k8s_rag"
            - name: NEO4J_URI
              value: "bolt://neo4j-service:7687"
            - name: NEO4J_USER
              value: "neo4j"
            - name: NEO4J_PASSWORD
              value: "rag-assistant"
            - name: OLLAMA_HOST
              value: "http://ollama-service:11434"
            - name: OLLAMA_MODEL
              value: "phi3:mini"
            - name: TOP_K
              value: "3"
---
apiVersion: v1
kind: Service
metadata:
  name: query-api-service
  namespace: rag-assistant
spec:
  selector:
    app: query-api
  ports:
    - port: 8000
      targetPort: 8000
  type: NodePort
  